var myArray = [
    "Hello/안녕하세요",
    "Nice to meet you/반갑습니다",
    "Thank you/감사합니다",
    "Excuse me/잠시만요",
    "I’m sorry (informal)/죄송합니다",
    "I'm sorry (formal)/미안합니다",
    "Please/주세요",
    "This one/이것",
    "Where is the [x]/[x] 어디예요",
    "Remove/빼주세요",
    "Beer/맥주",
    "Soju/소주",
    "Right/오른",
    "Left/왼",
    "Straight/직진",
    "How much is it?/얼마예요",
    "Give me a discount/깎아주세요",
    "Is there a/있어요",
    "I can’t speak Korean well/한국말 잘 못해요",
    "What’s new?/별일 없지요 ?",
    "Long time no see/오랜만이다",
    "I am very happy to meet you/만나서 참 반가워요",
    "Yes/네",
    "No/아니요",
    "Excuse me (to request something)/실례지만…",
    "You’re welcome / don’t mention it/천만 에 요",
    "What?/뭐?",
    "What music do you like?/어떤 음악 을 좋아해요 ?",
    "What do you do when you have free time?/시간 있을 때 뭐 하세요 ?",
    "What does this mean?/무슨 뜻이에요?",
    "Please say that one more time./다시 한 번 말해 주세요.",
    "Please speak slowly./천천히 말해 주세요.",
    "Please write it down./적어 주세요",
    "I don’t understand/모르겠 습니 다",
    "Sometimes/가끔",
    "Always/항상",
    "Today/오늘",
    "Tomorrow/내일",
    "Yesterday/어제",
    "Well…/글쎄요…",
    "Um/음",
    "Oh my gosh/헐",
    "For real?/진짜요?",
    "I think so/저도 그렇게 생각 합니다",
    "See you later/나중에 봬요",
    "Good bye/안녕히 계세요",
    "Have a nice day/좋은 하루 되세요",
    "See you later./이따 봐요",
    "I have to go now/나 지금 가야 돼",
    "A thing or an object/것",
    "To do/하다",
    "To be/있다",
    "way, method, Number/수",
    "I/나",
    "absent/없다",
    "To not do/ 않다",
    "Person/사람",
    "we, our/우리",
    "He, That/그",
    "To not be/아니다",
    "To try/보다",
    "thing/거",
    "To see/보다",
    "To be similar/같다",
    "To give, to do for a person/주다",
    "Face, confront/대하다",
    "To go/가다",
    "Year/년",
    "One, a single/한",
    "words, speaking/말",
    "Work/일",
    "A person, This/이",
    "Speak/말하다",
    "To do for the sake of/위하다",
    "but still, however/그러나",
    "To come/오다",
    "To know/알다",
    "Mr./씨",
    "That is right/그렇다",
    "To be big, large/크다",
    "culture/사회",
    "many/많다",
    "To be good/좋다",
    "More/더",
    "Receive/받다",
    "That thing/그것",
    "House/집",
    "Come out/나오다",
    "and then/그리고",
    "question, problem/문제",
    "Such a/그런",
    "To live/살다",
    "That/저",
    "Be impossible/못하다",
    "To think/생각하다",
    "To not know/모르다",
    "The inside/속",
    "To make/만들다",
    "Place, point, instance/데",
    "In front of, before/앞",
  ];
  
export {myArray};